@echo * Retrieving packages from NuGet...
@nuget install -ConfigFile packages.config -OutputDirectory packages
@echo * Copying library to bin folder...
@copy packages\Newtonsoft.Json.8.0.2\lib\net45\Newtonsoft.Json.dll bin\Newtonsoft.Json.dll /Y